  
  // This is not a complete set of all the location you can search in the API
  // There are still alot locations that didn't include in this list
  // The locations you are searching might not suggest in the search box
  // But you can still search them if they are available in the API

const citiesList = [

  "Abidjan",
  "Alaska",
  "Africa",
  "Abu Dhabi",
  "Abuja",
  "Accra",
  "Addis Ababa",
  "Ahmedabad",
  "Aleppo",
  "Alexandria",
  "Algiers",
  "Almaty",
  "Amman",
  "Amsterdam",
  "Anchorage",
  "Andorra la Vella",
  "Ankara",
  "Antananarivo",
  "Apia",
  "Arnold",
  "Ashgabat",
  "Asmara",
  "Asuncion",
  "Athens",
  "Auckland",
  "Avarua",
  "Baghdad",
  "Baku",
  "Bamako",
  "Banda Aceh",
  "Bandar Seri Begawan",
  "Bandung",
  "Bangkok",
  "Bangui",
  "Banjul",
  "Barcelona",
  "Barranquilla",
  "Basrah",
  "Basse-Terre",
  "Basseterre",
  "Beijing",
  "Beirut",
  "Bekasi",
  "Belem",
  "Belgrade",
  "Belmopan",
  "Belo Horizonte",
  "Bengaluru",
  "Berlin",
  "Bern",
  "Bishkek",
  "Bissau",
  "Bogota",
  "Brasilia",
  "Bratislava",
  "Brazzaville",
  "Bridgetown",
  "Brisbane",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Buenos Aires",
  "Bujumbura",
  "Bursa",
  "Busan",
  "Cairo",
  "Cali",
  "Caloocan",
  "Camayenne",
  "Canberra",
  "Cape Town",
  "Caracas",
  "Casablanca",
  "Castries",
  "Cayenne",
  "Charlotte Amalie",
  "Chengdu",
  "Chennai",
  "Chicago",
  "Chisinau",
  "Chittagong",
  "Chongqing",
  "Colombo",
  "Conakry",
  "Copenhagen",
  "Cordoba",
  "Curitiba",
  "Daegu",
  "Daejeon",
  "Dakar",
  "Dallas",
  "Damascus",
  "Dar es Salaam",
  "Delhi",
  "Denver",
  "Dhaka",
  "Dili",
  "Dodoma",
  "Doha",
  "Dongguan",
  "Douala",
  "Douglas",
  "Dubai",
  "Dublin",
  "Durban",
  "Dushanbe",
  "Faisalabad",
  "Fort-de-France",
  "Fortaleza",
  "Freetown",
  "Fukuoka",
  "Funafuti",
  "Gaborone",
  "George Town",
  "Georgetown",
  "Gitega",
  "Giza",
  "Guadalajara",
  "Guangzhou",
  "Guatemala City",
  "Guayaquil",
  "Gujranwala",
  "Gustavia",
  "Gwangju",
  "Hamburg",
  "Hanoi",
  "Harare",
  "Havana",
  "Helsinki",
  "Ho Chi Minh City",
  "Honiara",
  "Honolulu",
  "Houston",
  "Hyderabad",
  "Hyderabad",
  "Ibadan",
  "Incheon",
  "Isfahan",
  "Islamabad",
  "Istanbul",
  "Izmir",
  "Jaipur",
  "Jakarta",
  "Jeddah",
  "Jerusalem",
  "Johannesburg",
  "Juarez",
  "Juba",
  "Kabul",
  "Kaduna",
  "Kampala",
  "Kano",
  "Kanpur",
  "Kaohsiung",
  "Karachi",
  "Karaj",
  "Kathmandu",
  "Kawasaki",
  "Kharkiv",
  "Khartoum",
  "Khulna",
  "Kigali",
  "Kingsburg",
  "Kingston",
  "Kingstown",
  "Kinshasa",
  "Kobe",
  "Kolkata",
  "Kota Bharu",
  "Kowloon",
  "Kuala Lumpur",
  "Kumasi",
  "Kuwait",
  "Kyiv",
  "Kyoto",
  "La Paz",
  "Lagos",
  "Lahore",
  "Libreville",
  "Lilongwe",
  "Lima",
  "Lisbon",
  "Ljubljana",
  "Lome",
  "London",
  "Los Angeles",
  "Luanda",
  "Lubumbashi",
  "Lusaka",
  "Luxembourg",
  "Macau",
  "Madrid",
  "Majuro",
  "Makassar",
  "Malabo",
  "Male",
  "Mamoudzou",
  "Managua",
  "Manama",
  "Manaus",
  "Manila",
  "Maputo",
  "Maracaibo",
  "Maracay",
  "Mariehamn",
  "Marigot",
  "Maseru",
  "Mashhad",
  "Mbabane",
  "Mecca",
  "Medan",
  "Medellin",
  "Medina",
  "Melbourne",
  "Mexico City",
  "Mexico",
  "Miami",
  "Minsk",
  "Mogadishu",
  "Monrovia",
  "Montevideo",
  "Montreal",
  "Moroni",
  "Moscow",
  "Mosul",
  "Multan",
  "Mumbai",
  "Muscat",
  "N'Djamena",
  "Nagoya",
  "Nairobi",
  "Nanchong",
  "Nanjing",
  "Nassau",
  "Nay Pyi Taw",
  "New York",
  "Niamey",
  "Nicosia",
  "Nouakchott",
  "Noumea",
  "Novosibirsk",
  "Nuku'alofa",
  "Nur-Sultan",
  "Nuuk",
  "Oranjestad",
  "Osaka",
  "Oslo",
  "Ottawa",
  "Ouagadougou",
  "Pago Pago",
  "Palembang",
  "Palo Alto",
  "Papeete",
  "Paramaribo",
  "Paris",
  "Perth",
  "Philadelphia",
  "Phnom Penh",
  "Phoenix",
  "Podgorica",
  "Port Louis",
  "Port Moresby",
  "Port of Spain",
  "Port-Vila",
  "Port-au-Prince",
  "Porto Alegre",
  "Porto-Novo",
  "Prague",
  "Praia",
  "Pretoria",
  "Pristina",
  "Puebla",
  "Pune",
  "Pyongyang",
  "Quezon City",
  "Quito",
  "Rabat",
  "Rawalpindi",
  "Recife",
  "Reykjavik",
  "Riga",
  "Rio de Janeiro",
  "Riyadh",
  "Road Town",
  "Rome",
  "Roseau",
  "Saint George's",
  "Saint Helier",
  "Saint John's",
  "Saint Peter Port",
  "Saint Petersburg",
  "Saint-Denis",
  "Saint-Pierre",
  "Saipan",
  "Salvador",
  "San Antonio",
  "San Diego",
  "San Francisco",
  "San Jose",
  "San Juan",
  "San Marino",
  "San Salvador",
  "Sanaa",
  "Santa Cruz de la Sierra",
  "Santiago",
  "Santo Domingo",
  "Sao Paulo",
  "Sao Tome",
  "Sapporo",
  "Sarajevo",
  "Seattle",
  "Semarang",
  "Seoul",
  "Shanghai",
  "Sharjah",
  "Shenzhen",
  "Skopje",
  "Sofia",
  "South Tangerang",
  "Soweto",
  "Stockholm",
  "Sucre",
  "Surabaya",
  "Surat",
  "Suva",
  "Sydney",
  "Tabriz",
  "Taipei",
  "Tallinn",
  "Tangerang",
  "Tarawa",
  "Tashkent",
  "Tbilisi",
  "Tegucigalpa",
  "Tehran",
  "Tel Aviv",
  "Thimphu",
  "Tianjin",
  "Tijuana",
  "Tirana",
  "Tokyo",
  "Toronto",
  "Torshavn",
  "Tripoli",
  "Tunis",
  "Ulan Bator",
  "Vaduz",
  "Valencia",
  "Valletta",
  "Vancouver",
  "Victoria",
  "Vienna",
  "Vientiane",
  "Vilnius",
  "Warsaw",
  "Washington",
  "Wellington",
  "Willemstad",
  "Windhoek",
  "Wuhan",
  "Xi'an",
  "Yamoussoukro",
  "Yangon",
  "Yaounde",
  "Yekaterinburg",
  "Yerevan",
  "Yokohama",
  "Zagreb",
  "Ivory Coast",
  "United Arab Emirates",
  "Ghana",
  "Ethiopia",
  "Algeria",
  "Jordan",
  "Netherlands",
  "United States",
  "Andorra",
  "Madagascar",
  "Samoa",
  "Turkmenistan",
  "Eritrea",
  "Paraguay",
  "Greece",
  "New Zealand",
  "Cook Islands",
  "Azerbaijan",
  "Mali",
  "Indonesia",
  "Brunei",
  "Thailand",
  "Central African Republic",
  "Gambia",
  "Guadeloupe",
  "Saint Kitts and Nevis",
  "Lebanon",
  "Serbia",
  "Belize",
  "Germany",
  "Switzerland",
  "Kyrgyzstan",
  "Guinea-Bissau",
  "Slovakia",
  "Republic of the Congo",
  "Barbados",
  "Belgium",
  "Romania",
  "Hungary",
  "Saint Lucia",
  "French Guiana",
  "U.S. Virgin Islands",
  "Moldova",
  "Sri Lanka",
  "Guinea",
  "Denmark",
  "Argentina",
  "Senegal",
  "Syria",
  "Bangladesh",
  "Timor Leste",
  "Djibouti",
  "Tanzania",
  "Qatar",
  "Cameroon",
  "Isle of Man",
  "Ireland",
  "Tajikistan",
  "Martinique",
  "Sierra Leone",
  "Japan",
  "Tuvalu",
  "Botswana",
  "Malaysia",
  "Guyana",
  "Gibraltar",
  "Burundi",
  "Egypt",
  "Guatemala",
  "Saint Barthelemy",
  "Zimbabwe",
  "Cuba",
  "Finland",
  "Vietnam",
  "Hong Kong",
  "Solomon Islands",
  "Iran",
  "Turkey",
  "South Sudan",
  "Afghanistan",
  "Uganda",
  "Nigeria",
  "Nepal",
  "Ukraine",
  "Sudan",
  "Rwanda",
  "Jamaica",
  "Saint Vincent and the Grenadines",
  "Democratic Republic of the Congo",
  "Kuwait",
  "Ukraine",
  "Gabon",
  "Malawi",
  "Peru",
  "Portugal",
  "Slovenia",
  "Togo",
  "United Kingdom",
  "Angola",
  "Zambia",
  "Luxembourg",
  "Macao",
  "Spain",
  "Marshall Islands",
  "Equatorial Guinea",
  "Maldives",
  "Mayotte",
  "Nicaragua",
  "Bahrain",
  "Mozambique",
  "Aland Islands",
  "Saint Martin",
  "Lesotho",
  "Eswatini",
  "Colombia",
  "Saudi Arabia",
  "Belarus",
  "Somalia",
  "Monaco",
  "Liberia",
  "Uruguay",
  "Canada",
  "Comoros",
  "Russia",
  "Iraq",
  "Oman",
  "Chad",
  "Kenya",
  "Bahamas",
  "Myanmar",
  "Niger",
  "Cyprus",
  "Mauritania",
  "New Caledonia",
  "Tonga",
  "Kazakhstan",
  "Greenland",
  "Aruba",
  "Norway",
  "Burkina Faso",
  "American Samoa",
  "Panama",
  "French Polynesia",
  "Suriname",
  "France",
  "Cambodia",
  "Montenegro",
  "Mauritius",
  "Papua New Guinea",
  "Trinidad and Tobago",
  "Vanuatu",
  "Haiti",
  "Benin",
  "Czechia",
  "Cabo Verde",
  "Kosovo",
  "North Korea",
  "Korea",
  "Philippines",
  "Ecuador",
  "Morocco",
  "Pakistan",
  "Iceland",
  "Latvia",
  "Brazil",
  "British Virgin Islands",
  "Italy",
  "Dominica",
  "Grenada",
  "Jersey",
  "Antigua and Barbuda",
  "Guernsey",
  "Reunion",
  "Reunion",
  "Northern Mariana Islands",
  "El Salvador",
  "Yemen",
  "Chile",
  "Dominican Republic",
  "Sao Tome and Principe",
  "Bosnia and Herzegovina",
  "South Korea",
  "Singapore",
  "North Macedonia",
  "Bulgaria",
  "South Africa",
  "Sweden",
  "Bolivia",
  "India",
  "Fiji",
  "Australia",
  "Taiwan",
  "Estonia",
  "Kiribati",
  "Uzbekistan",
  "Georgia",
  "Honduras",
  "Israel",
  "Bhutan",
  "Albania",
  "Faroe Islands",
  "Libya",
  "Tunisia",
  "Mongolia",
  "Liechtenstein",
  "Venezuela",
  "Malta",
  "Austria",
  "Laos",
  "Lithuania",
  "Poland",
  "Curacao",
  "Namibia",
  "Armenia",
  "Croatia",
  "Albuquerque",
  "New Mexico",
  "Pentagon",
  "England",
  "Alabama",
  "Arizona"
]

export default citiesList