import Head from 'next/head'
import { useEffect } from 'react'
import BgWeather from '../components/BgWeather'
import Details from '../components/Details'
import SearchBar from '../components/SearchBar'
import Temp from '../components/Temp'
import callWeather from '../utils/callWeather'

export default function Home() {

  const { weather, getWeather } = callWeather()
  
  const getLocation = (location) => {
    getWeather(location)
  }

  if (Object.keys(weather).length === 0) {
    getWeather('bangkok')
  }

  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='relative w-full h-screen overflow-hidden'>
        <BgWeather 
          // timezone={new Date(weather.dt*1000)}
          weather={weather.weather ? weather.weather[0].description : null}
        />
      
        <div className='relative z-20 max-w-[800px] h-full border-2 mx-auto py-20'>
          <div>
            <div>{weather.name}</div>
            <div>{weather.weather ? weather.weather[0].icon : null}</div>
            <div>{weather.weather ? weather.weather[0].description : null}</div>
            {/* <div>{getDate(weather.dt)}</div> */}
            <div>{weather.timezone}</div>
            <div>{weather.temp}</div>
            <div>{weather.humidity}</div>
            <div>{weather.wind ? weather.wind.speed : null}</div>
          </div>
          <SearchBar 
            location={getLocation}
          />
          {/* <Temp 
            location={weather.name}
            icon={weather.weather[0].icon}
            desc={weather.weather[0].description}
            timezone={weather.timezone}
          />
          <Details 
            temp={weather.temp}
            humidity={weather.humidity}
            speed={weather.wind.speed}
          /> */}

        </div>

      </main>
    </div>
  )
}
